auth_db_connect_string = "host=localhost user=camp_test password='camp_test' dbname=camp_auth_fakeprod"
data_db_connect_string = "host=localhost user=camp_test password='camp_test' dbname=camp_store_fakeprod"