auth_db_connect_string = "host=localhost user=camp_test password='camp_test' dbname=camp_auth_fakeprod"
data_db_connect_string = "host=localhost user=camp_test password='camp_test' dbname=camp_store_fakeprod"
sendgrid_auth_string = "Yabba dabba doo!"
pandoc_uri = "https://pandocker-kbps2bpktq-ue.a.run.app"
pandoc_auth = "frog"
pandoc_format = "markdown+smart"